title : "Compute the indicators for each Labdoc version"
# ======================================= vars =======================================================================================
vars : 
  db : 
    user : "root"
    password : 11950022
    host : "localhost"
    database : "Labnbook"
  regex :
    regex_text : "configs/regex_text.json"
  result : "collab.json.gz"
  visualization :
    id_labdoc : 288282
    id_report : 31489
    id_mission : 1044



 # ============================================ directories ===========================================================================

directories : ["model","scripts","versioning","configs"]
model:
  - dest: "model/fr_LabnbookNer-0.0.0"
    description: "The 'fr_LabNbookNer-VERSION' folder and the 'components.py' file that contains a specific SpaCy components. Theses files are a copy if the correct_ner subproject."
scripts:
  - dest: "scripts/*.py"
    description: "Contain all the scripts used to compute the indicators"
configs:
  - dest: "configs/config.cfg"
    description: "The config file of the model 'fr_LabnbookNer-0.0.0'  needed to use it"
versioning:
  - dest: "versioning/*.json"
    description: "The versioning files of each labdoc"

# ================================================workflows=======================================================================

workflows : 
      extract_labdoc_text_versions :
        - extract_labdoc_text_init
        - extract_labdoc_text
      compute_contributions_matrices : 
        - contrib_and_segmentation
        - collaboration 
        - report
        - readme

# ===================================================commands=======================================================================

commands : 
    - name: "extract_labdoc_text_init"
      help: "Get the id of text labdocs as well as the initial texts (with html tags) written by teachers."
      script:
        - "python3 scripts/extract_labdoc_text_init.py ${vars.db.user} ${vars.db.password} ${vars.db.host} ${vars.db.database}"
      outputs:
        - "tmp/labdocs_texts_init.json.gz"
##  ----------------------------------------------------------------------------------------------------------------------
    - name: "extract_labdoc_text"
      help: "Extracts the text of each version of labdoc by removing the html tags and clean texts according to regex patterns."
      script:
        - "python3 scripts/extract_labdoc_text.py ${vars.regex.regex_text}"
      outputs:
        - "tmp/missions_texts/"
##  ----------------------------------------------------------------------------------------------------------------------
    - name: "contrib_and_segmentation"
      help: ""
      script:
        - "python3 scripts/contrib_and_segmentation.py"
      deps:
        - "tmp/missions_texts/"
      outputs:
        - "/tmp/missions_contribs/"
##  ----------------------------------------------------------------------------------------------------------------------
    - name: "collaboration"
      help: ""
      script:
        - "python3 scripts/collaboration.py"
      deps:
        - "tmp/missions_texts/"
      outputs:
        - "tmp/collab.json.gz"
        - "tmp/collab.csv"
##  ----------------------------------------------------------------------------------------------------------------------
    - name: "report"
      help: "Compute some reports about the indicators for each labdoc."
      script:
        - "python3 scripts/summary.py tmp/${vars.result}"
      deps:
        - "tmp/collab.json.gz"
      outputs:
        - "tmp/summary.csv"
## ----------------------------------------------------------------------------------------------------------------------
    - name: readme
      help: "Create a readme file"
      script:
        - "python -m spacy project document --output README.md"

      outputs:
        - "README.md"
## ----------------------------------------------------------------------------------------------------------------------